github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://apps.serp.co/hdzog-downloader",
  "https://serp.co/products/hdzog-downloader/reviews/",
  "https://extensions.serp.co/hdzog-downloader",
  "https://browserextensions.io/hdzog-downloader"
]
